View_statistics: 'Просмотреть статистику'
'Uploaded videos': 'Популярные за неделю'
'last added': 'Последние добавленные'
'Popular for the week': 'Популярные за неделю'
'Dislike cheats analytics': 'Анализатор накрутки дизлайков'
'Measuring the number of likes, dislikes, views, comments': 'измерение количества лайков, дизлайков, просмотров, комментариев'
Enter-Youtube-video-id: 'Введите Youtube video id'
Upload-as-admin: 'Добавить как админ'
Upload: 'Добавить'
For-example: 'Например'
Only-id: 'Только id'
website-addresses: 'адреса сайта'
Tags: 'Теги'
Loading: 'Загрузка...'
January: 'Январь'
February: 'Февраль'
March: 'Март'
April: 'Апрель'
May: 'Май'
June: 'Июнь'
July: 'Июль'
August: 'Август'
September: 'Сентябрь'
October: 'Октябрь'
November: 'Ноябрь'
December: 'Декабрь'
Sunday: 'Воскресенье'
Monday: 'Понедельник'
Tuesday: 'Вторник'
Wednesday: 'Среда'
Thursday: 'Четверг'
Friday: 'Пятница'
Saturday: 'Суббота'
Jan: 'Янв'
Feb: 'Фев'
Apr: 'Апр'
Aug: 'Авг'
Sep: 'Сент'
Oct: 'Окт'
Nov: 'Нояб'
Dec: 'Дек'
Export: "Экспорт"
Print: "Печать"
From: "От"
To: "До"
Zoom-in: "Увеличить"
Download: 'Скачать'
Print-chart: 'Напечатать график'
Context-menu: 'Контекстное меню'
Reset: 'Сбросить'
Reset-zoom-to: 'Сбросить увеличение к'
Metrics: 'Показатели'
Time: 'Время'
Qty: 'Кол-во'
click: 'Клик'
'on the title of the chart to turn it on / off. "Delta" - schedules of speed of change, units per minute.': ' на название графика включает/выключает его. "-Дельта" - графики скорости изменения, единиц в минуту.'
No-spaces-symbols: 'Без пробелов, символов'
likes: 'Лайки'
views: 'Просмотры'
comments: 'Комментарии'
dislikes: 'Дизлайки'
like-delta: 'Лайки-дельта'
dislike-delta: 'Дизлайки-дельта'
delta-views: 'Просмотры-дельта'
delta-comments: 'Комментарии-дельта'
subs: 'Подписчики'
subs-delta: 'Подписчики-дельта'
Video: 'Видео'
of_channel: 'канала'
Stats of video: 'Cтатистика видео'
measuring likes, dislikes, views and comments count: 'измерение количества лайков, дизлайков, просмотров, комментариев'
Channel: 'Канал'
Other channel`s videos: 'Другие видео канала'
meta-keyword: 'Статистика youtube, дизлайк метр,  сервис дизлайк метр, dislikemeter, сервис, dislikemeter, дизлайкметр, дизлайкометр, статистика лайков и дизлайков на ютубе, dislike meter, dislikemeter com, dislikemetr, дизлайкметер, дизлайк метр сервис, дизлайк омметр, dislikemeter.com'
Stats: 'Статистика'
at: 'на'
service_for_grab_data_of_cheating_on_youtube: 'сервис по сбору статисистики о накрутках на youtube'
Analyze params of channel: 'Анализ параметров канала'
video_successfully_added: 'Видео успешно добавлено! Сбор данных идёт пока видео находится в последних добавленных, либо попало в лучшие по кол-ву просмотров страницы.'
video_already_exists: 'Такое видео уже есть'
this_alert_will_be_removed_in: 'Данное оповещение будет убрано через'
channel_not_found: 'messages'
Statistics of changes in dislikes, likes, views: 'Статистика изменения дизлайков, лайков, просмотров'
