View_statistics: View statistics
'Uploaded videos': 'Uploaded videos'
'last added': 'Last added'
'Popular for the week': 'Popular this week'
'Dislike cheats analytics': 'Dislike cheats analytics'
'Measuring the number of likes, dislikes, views, comments': 'Measuring the number of likes, dislikes, views and comments'
Enter-Youtube-video-id: Enter a Youtube video ID
Upload-as-admin: Upload as admin
Upload: Upload
For-example: For example
Only-id: Only ID
website-addresses: website addresses
Tags: Tags
Loading: Loading
January: January
February: February
March: March
April: April
May: May
June: June
July: July
August: August
September: September
October: October
November: November
December: December
Sunday: Sunday
Monday: Monday
Tuesday: Tuesday
Wednesday: Wednesday
Thursday: Thursday
Friday: Friday
Saturday: Saturday
Jan: Jan
Feb: Feb
Apr: Apr
Aug: Aug
Sep: Sep
Oct: Oct
Nov: Nov
Dec: Dec
Export: Export
Print: Print
From: From
To: To
Zoom-in: Zoom in
Download: Download
Print-chart: Print chart
Context-menu: Context menu
Reset: Reset
Reset-zoom-to: Reset zoom to
Metrics: Metrics
Time: Time
Qty: Qty
click: click
'on the title of the chart to turn it on / off. "Delta" - schedules of speed of change, units per minute.': 'on the name of the metric to show it or hide it. "-delta" - shows the change of a metric per minute.'
No-spaces-symbols: 'No spaces, symbols'
likes: Likes
views: Views
comments: Comments
dislikes: Dislikes
like-delta: Like delta
dislike-delta: Dislike delta
delta-views: Views delta
delta-comments: Comments delta
subs: 'Subscribers'
subs-delta: 'Subscribers delta'
Video: Video
of_channel: 'of the channel'
Stats of video: 'Stats of the video'
measuring likes, dislikes, views and comments count: 'measuring the count of likes, dislikes, views and comments'
Channel: Channel
Other channel`s videos: Other videos of the channel
meta-keyword: 'Statistics youtube, dislike meter, service dislikemeter, dislikemeter, service, dislikemeter, dizlaykmet, dizlaykometer, statistics of likes and dislikes on YouTube, dislike meter, dislikemeter com, dislikemetr, deslaymeter, dislike meter service, dislike ohmmeter, dislikemeter.com'
Stats: 'Statistics'
at: 'at'
service_for_grab_data_of_cheating_on_youtube: 'Service for grabbing data of cheating on YouTube'
Analyze params of channel: 'Analyze params of channel'
video_successfully_added: 'Video successfully added'
video_already_exists: 'Video already exists'
this_alert_will_be_removed_in: 'This alert will be removed in'
channel_not_found: 'Channel not found'
Statistics of changes in dislikes, likes, views: 'Statistics of changes in dislikes, likes, views'
